# Documentation Indexer Configuration

# OpenAI Settings
openai:
  model_name: "gpt-4"
  temperature: 0

# Document Processing Settings
document:
  chunk_size: 1000
  chunk_overlap: 100

# Vector Store Settings
vector_store:
  index_path: "faiss_index"
  similarity_search_k: 4  # Number of similar documents to retrieve

# URLs to index
urls:
  - "https://experienceleague.adobe.com/docs/analytics/analyze/home.html"

# URL Pattern Restrictions
url_patterns:
  accepted:
    - "*/docs/analytics/*"
    - "*/docs/data-collection/*"
  blacklisted:
    - "*/implementation/*"
    - "*/admin/*"
    - "*/deprecated/*"
    - "*/legacy/*"
    - "*/login/*"
    - "*/signup/*"

# Prompt Template
prompt_template: |
  Use the following pieces of context to answer the question at the end. 
  If you don't know the answer, just say that you don't know, don't try to make up an answer.

  Context: {context}

  Question: {question}
  Answer: 